server:
  port: 7071

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/easylive
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
      database: 0
      timeout: 2000
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

openProject:
  isOpen: true
  cmd: cmd   /c   start
  web:
    openUrl: http://localhost:${server.port}/#

project:
  folder: c:/computer science/live_info/
log:
  root:
    level: debug
admin:
  account: root
  password: 12345